spring:
  application:
    name: Config-Default
eureka:
  instance:
    prefer-ip-address: true
    appname: USER-SERVICE
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: {
                   defaultZone:http://localhost:8761/eureka
    }
